AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - test/**/*
Style/Documentation:
  Enabled: false
